"""
run_pipeline.py — End-to-end ThreatLens pipeline.

Parses raw logs -> runs detection engine -> stores alerts in SQLite.
Run this after generating logs (src/generator.py) to populate the
database that the dashboard (dashboard/app.py) reads from.
"""

import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parent / "src"))

from parser import parse_log_file
from detectors import run_all_detectors
from db import init_db, insert_alerts, get_summary_stats
from alerter import notify_high_severity

DATA_DIR = Path(__file__).resolve().parent / "data"


def main():
    print("=" * 50)
    print("ThreatLens Pipeline")
    print("=" * 50)

    # Step 1: ensure DB exists
    init_db()

    # Step 2: parse logs
    auth_log_path = DATA_DIR / "sample_auth.log"
    if not auth_log_path.exists():
        print(f"[!] {auth_log_path} not found. Run src/generator.py first.")
        return

    print(f"[+] Parsing {auth_log_path} ...")
    df = parse_log_file(str(auth_log_path), log_type="auth")
    print(f"[+] Parsed {len(df)} log events "
          f"({df['event_type'].nunique()} distinct event types)")

    # Step 3: run detection engine
    print("[+] Running detection engine ...")
    alerts = run_all_detectors(df)
    print(f"[+] {len(alerts)} alerts generated by detectors")

    # Step 4: store alerts
    inserted = insert_alerts(alerts)
    print(f"[+] {inserted} new alerts inserted into database "
          f"({len(alerts) - inserted} duplicates skipped)")

    notified = notify_high_severity(alerts)
    if notified:
        print(f"[+] {notified} High-severity webhook notification(s) sent")

    # Step 5: summary
    stats = get_summary_stats()
    print("-" * 50)
    print(f"Total alerts in DB : {stats['total_alerts']}")
    print(f"High severity      : {stats['high_severity']}")
    print(f"Unique attacker IPs: {stats['unique_ips']}")
    print("=" * 50)
    print("[+] Pipeline complete. Run `streamlit run dashboard/app.py` to view results.")


if __name__ == "__main__":
    main()
